/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.laudy.group;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int anime=0x7f020000;
        public static final int custom_rectangle=0x7f020001;
        public static final int fb=0x7f020002;
        public static final int ic_account_user=0x7f020003;
        public static final int ic_add_black_24dp=0x7f020004;
        public static final int ic_contact_picture_180_holo=0x7f020005;
        public static final int ic_launcher=0x7f020006;
        public static final int ic_launcher_foreground=0x7f020007;
        public static final int ic_launcher_mail=0x7f020008;
        public static final int ic_material_credit_card=0x7f020009;
        public static final int ic_material_local_shipping=0x7f02000a;
        public static final int ic_menu_buy=0x7f02000b;
        public static final int ic_menu_chat=0x7f02000c;
        public static final int ic_menu_home=0x7f02000d;
        public static final int ic_menu_phone=0x7f02000e;
        public static final int ic_menu_search=0x7f02000f;
        public static final int ic_remove_black_24dp=0x7f020010;
        public static final int ic_shopping_cart_black_24dp=0x7f020011;
        public static final int ig=0x7f020012;
        public static final int laudy=0x7f020013;
        public static final int launcher_icon_fblite=0x7f020014;
        public static final int store_item_background=0x7f020015;
        public static final int whatsapp=0x7f020016;
    }
    public static final class id {
        public static final int actbarEdt=0x7f070000;
        public static final int actbarImg=0x7f070001;
        public static final int add=0x7f07004c;
        public static final int addKat=0x7f07004d;
        public static final int akun=0x7f070005;
        public static final int akunMember=0x7f070035;
        public static final int alamat=0x7f07000d;
        public static final int bayarharga=0x7f070008;
        public static final int bayarnama=0x7f070007;
        public static final int beranda=0x7f070002;
        public static final int btnAkunSukses=0x7f07003b;
        public static final int btnAkunSuksesClient=0x7f07003d;
        public static final int btnAkunSuksesTroll=0x7f07003c;
        public static final int btnBuy=0x7f070046;
        public static final int btnFoto=0x7f07001c;
        public static final int btnFotoProfil=0x7f070014;
        public static final int btnKata=0x7f070019;
        public static final int btnKataHapus=0x7f07001e;
        public static final int btnKoment=0x7f070047;
        public static final int btnLogin=0x7f070034;
        public static final int btnPembayaran=0x7f070006;
        public static final int btnSign=0x7f070036;
        public static final int btnWelcome=0x7f07004a;
        public static final int btnfotopdk=0x7f070010;
        public static final int callEmail=0x7f07003f;
        public static final int callFb=0x7f070040;
        public static final int callIG=0x7f070041;
        public static final int callWhats=0x7f07003e;
        public static final int edtLoginName=0x7f070031;
        public static final int edtLoginPass=0x7f070033;
        public static final int edtNama=0x7f07000b;
        public static final int edtProfilNama=0x7f070012;
        public static final int edtProfilPass=0x7f070013;
        public static final int edtSignAlam=0x7f070018;
        public static final int edtSignNama=0x7f070016;
        public static final int edtSignPass=0x7f070017;
        public static final int edtadd=0x7f07001a;
        public static final int edtaddhar=0x7f07001b;
        public static final int edtaddkatagori=0x7f07001f;
        public static final int edthpdk=0x7f07000f;
        public static final int edtpdk=0x7f07000e;
        public static final int fotoprofil=0x7f070039;
        public static final int gridtroll=0x7f070042;
        public static final int gridview=0x7f070027;
        public static final int hapusKat=0x7f07004e;
        public static final int harga=0x7f070024;
        public static final int hargaView=0x7f070045;
        public static final int imageFoto=0x7f07001d;
        public static final int imageFotoProfil=0x7f070015;
        public static final int imagepFoto=0x7f070011;
        public static final int imgAkun=0x7f07002d;
        public static final int imgFBeli=0x7f070026;
        public static final int imgFeed=0x7f07002a;
        public static final int imgFrag=0x7f070022;
        public static final int imgHome=0x7f070029;
        public static final int imgPesan=0x7f07002b;
        public static final int imgTroll=0x7f07002c;
        public static final int imgView=0x7f070043;
        public static final int imgmemberProfil=0x7f070021;
        public static final int keterangan=0x7f070023;
        public static final int koment=0x7f070025;
        public static final int komentList=0x7f070049;
        public static final int komentView=0x7f070048;
        public static final int layout_main=0x7f07002e;
        public static final int menabout=0x7f070050;
        public static final int menprofile=0x7f07004f;
        public static final int mylayout=0x7f07004b;
        public static final int pesan=0x7f070003;
        public static final int selection=0x7f070028;
        public static final int titNama=0x7f070030;
        public static final int titPass=0x7f070032;
        public static final int titleAkun=0x7f07002f;
        public static final int titleAkunDate=0x7f070037;
        public static final int titleAkunLogout=0x7f070038;
        public static final int titleAkunSukses=0x7f07003a;
        public static final int troll=0x7f070004;
        public static final int txtAlamat=0x7f07000c;
        public static final int txtNama=0x7f07000a;
        public static final int txtToko=0x7f070009;
        public static final int txtView=0x7f070044;
        public static final int txtmemberprofil=0x7f070020;
    }
    public static final class layout {
        public static final int actionbar=0x7f030000;
        public static final int add=0x7f030001;
        public static final int alert_beli=0x7f030002;
        public static final int alert_edit=0x7f030003;
        public static final int alert_edit_profil=0x7f030004;
        public static final int alert_sign=0x7f030005;
        public static final int alert_tambah=0x7f030006;
        public static final int alert_tambah_katagori=0x7f030007;
        public static final int alert_viewmember=0x7f030008;
        public static final int frag=0x7f030009;
        public static final int fragmentku=0x7f03000a;
        public static final int main=0x7f03000b;
        public static final int main_akun=0x7f03000c;
        public static final int main_akun_sukses=0x7f03000d;
        public static final int main_call=0x7f03000e;
        public static final int main_tab=0x7f03000f;
        public static final int main_troll=0x7f030010;
        public static final int main_view=0x7f030011;
        public static final int main_welcome=0x7f030012;
    }
    public static final class menu {
        public static final int actions=0x7f060000;
        public static final int actions_member=0x7f060001;
    }
    public static final class string {
        public static final int action_settings=0x7f050002;
        public static final int app_name=0x7f050000;
        public static final int hello_world=0x7f050001;
    }
}
